### ISSUE TITLE
Amethyst Block Variants (+more possibly) not working

### ISSUE THREAD

**Issue by Shrimpton** [Ametrin-Studios/BlockVariants#1]
**Describe the bug**
Downloaded the mod almost specifically to make amethyst block variants for a build. The blocks in question would not show up as having a craft recipe on JEI. I tried to craft slabs off the top of my head using amethyst blocks and shards in the traditional 3x1 style on crafting table but it would not allow me to craft it. I right and left clicked on the JEI icon but nothing happened for amethyst slab, stair and wall. I also did this with a few other blocks from this mod which worked and did what it was supposed (could only be amethyst that doesn't work). Maybe I had the wrong recipe but that still means the JEI not working with it an issue.

**Screenshots**
can't acquire for this dilemma 

**Version**
 - [1.18.2]
 - Forge version: [40.1.0]
 - Block Variants version [3.2]

**Comment by BarionLP** [comment]
I couldn't check every block, but I fixed it and also saw that the same applies for Dripstone blocks. Do you need that fix fast or can I wait until the next update?

**Comment by Shrimpton** [comment]
> I couldn't check every block, but I fixed it and also saw that the same applies for Dripstone blocks. Do you need that fix fast or can I wait until the next update?

if its possible to fix it ASAP that would be great :)

thanks for getting it sorted so quickly!
 also will it show that the file on curse forge will be updated when its changed?

**Comment by BarionLP** [comment]
fix is out for 1.18.2 and 1.19
https://www.curseforge.com/minecraft/mc-mods/vanilla-block-variants/files/3859929

**Comment by Shrimpton** [comment]
i can build my base now :)
