### ISSUE TITLE
Failed to load correctly

### ISSUE THREAD

**Issue by HarryPlopper91** [Ametrin-Studios/BlockVariants#4]
**Minecraft v1.19.1**
**Forge v42.0.1**

`Block Variants (block_variants) has failed to load correctly`
`java.lang.NoClassDefFoundError: net/minecraftforge/forge/event/lifecycle/GatherDataEvent`

[PasteBin Link](https://pastebin.com/S9pXDDHr)

**Comment by HarryPlopper91** [comment]
Well before I get another dev coming to trash comment people that are trying to help them out (not saying you will but thats been the going rate so far). It looks like your publishing settings are incorrect on Curseforge as your publish date for this version shows as 7/5/2022 and 1.19.1 did not come out till a few days ago. I'm going to close this comment and recommend you update your Curseforge publishing settings to reflect that it is not compatible with 1.19.1 just yet.

![Screenshot 2022-07-31 125336](https://user-images.githubusercontent.com/98628933/182037017-82f95728-2cb4-4b7d-88c4-c44e1ec80639.png)

@BarionLP

**Comment by BarionLP** [comment]
you're right, that was my issue, guess I accidentally selected 1.19.1 as valid version

**Comment by HarryPlopper91** [comment]
Your not the only one unfortunately 😆
