### ISSUE TITLE
Publish on Modrinth?

### ISSUE THREAD

**Issue by allanonmage** [Ametrin-Studios/BlockVariants#5]
Please add your mod to Modrinth.  I like Modrinth because the search feature works, and you can filter by mod loader and version.

**Comment by BarionLP** [comment]
its not like that works for CurseForge perfectly too (at least since the great website update).

another website means more effort but i can take a look

**Comment by allanonmage** [comment]
Yeah I get it that it's a pain, but it seems that lots of people are leaving Curseforge for a variety of reasons.

**Comment by BarionLP** [comment]
https://modrinth.com/mod/block-variants 
took a while but now we are there
